# Generated by Django 2.1.3 on 2019-01-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190114_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PUB', 'Published'), ('NPUB', 'No Published')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
